"""
Step 4: 视频生成 (Wan2.2-TI2V-5B GGUF)
========================================
通过 ComfyUI API 调用 Wan2.2 生成视频。
使用 comfy-core 原生节点: UnetLoaderGGUF + CLIPLoaderGGUF + WanImageToVideo + KSampler

模型需求:
  - UNET: Wan2.2-TI2V-5B-Q4_K_M.gguf (5.1GB)
  - CLIP: umt5-xxl-encoder-Q4_K_M.gguf (3.6GB)
  - VAE: Wan2.2_VAE.safetensors (1.3GB)
  总计约10GB，T4 16GB 可用

工作流节点连接:
  UnetLoaderGGUF → KSampler.model
  CLIPLoaderGGUF → CLIPTextEncode.clip → KSampler.conditioning
  VAELoader → WanImageToVideo.vae
  EmptyLatentVideo → WanImageToVideo.latent
  WanImageToVideo → KSampler.latent_image
  CLIPTextEncode (positive/negative) → KSampler
  KSampler → VAEDecode → VHS_VideoCombine
"""

import os
import sys
import json
import time
import shutil
import urllib.request
import urllib.error
import subprocess
import threading

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import (
    log, save_json, load_json, run_cmd,
    EPISODE_NUM, get_dirs, MODEL_CACHE_DIR, DTYPE,
    WAN22_DEFAULTS,
)


# ============================================================
# ComfyUI 管理
# ============================================================

COMFYUI_URL = "http://127.0.0.1:8188"
COMFYUI_DIR = "/kaggle/working/ComfyUI"


def _find_comfyui():
    """查找 ComfyUI 安装位置（pip 安装 或 目录安装）"""
    # 方式1: pip 安装的 ComfyUI
    try:
        import importlib.util
        spec = importlib.util.find_spec("comfy")
        if spec and spec.origin:
            # 找到 comfy 包目录，返回其上级
            pkg_dir = os.path.dirname(spec.origin)
            # pip 安装时 comfy 包在 site-packages/comfy/
            # ComfyUI 可执行入口在同级的 main.py 或者用 python -m comfy
            return ("pip", pkg_dir)
    except:
        pass

    # 方式2: 目录安装
    for candidate in ["/kaggle/working/ComfyUI", "/kaggle/working/ComfyUI-master"]:
        if os.path.isdir(candidate) and os.path.isfile(f"{candidate}/main.py"):
            comfy_pkg = os.path.join(candidate, "comfy")
            server_py = os.path.join(candidate, "server.py")
            if os.path.isdir(comfy_pkg) and os.path.isfile(server_py):
                return ("dir", candidate)
            # 目录存在但不完整
            log(f"  ComfyUI 目录不完整，将重新安装")
            shutil.rmtree(candidate, ignore_errors=True)
    return None


def _install_comfyui():
    """安装 ComfyUI + GGUF 插件 (git clone 方式)"""
    # 清理旧进程
    run_cmd("pkill -f 'main.py' 2>/dev/null; true")

    if os.path.isdir(COMFYUI_DIR) and os.path.isfile(f"{COMFYUI_DIR}/main.py"):
        log(f"ComfyUI 目录存在: {COMFYUI_DIR}")
        # 检查依赖是否完整
        result = run_cmd("python -c 'import torch; import comfy; print(\"ok\")' 2>&1", timeout=30)
        if result.returncode == 0 and "ok" in result.stdout:
            log("  ComfyUI 依赖完整，跳过安装")
            _install_gguf_plugin()
            return
        log("  依赖不完整，重新安装...")

    log("安装 ComfyUI (git clone)...")
    # 删除旧目录
    if os.path.isdir(COMFYUI_DIR):
        shutil.rmtree(COMFYUI_DIR, ignore_errors=True)

    # git clone ComfyUI
    run_cmd(f"git clone https://github.com/comfyanonymous/ComfyUI.git {COMFYUI_DIR}",
            timeout=120)
    os.chdir(COMFYUI_DIR)

    # 安装依赖 (关键!)
    run_cmd("pip install -r requirements.txt 2>&1 | tail -5", timeout=300)
    run_cmd("pip install torchsde einops transformers safetensors aiohttp accelerate "
            "pyyaml opencv-python pillow scipy imageio[ffmpeg] moviepy "
            "huggingface_hub gguf pydantic-settings python-dotenv 2>&1 | tail -5",
            timeout=300)

    log("ComfyUI 安装完成")

    # GGUF 插件
    _install_gguf_plugin()
    # Video Helper 插件（提供 VHS_VideoCombine 等节点）
    _install_video_helper_plugin()


def _install_video_helper_plugin():
    """安装 comfyui-video-helper 插件（提供 VHS_VideoCombine 节点）"""
    cn_dir = f"{COMFYUI_DIR}/custom_nodes"
    vh_path = f"{cn_dir}/ComfyUI-VideoHelperSuite"
    if os.path.isdir(vh_path):
        return
    os.makedirs(cn_dir, exist_ok=True)
    log("  安装 Video Helper 插件...")
    run_cmd(
        f"git clone https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite.git {vh_path}",
        timeout=60,
    )
    # 安装依赖
    req = f"{vh_path}/requirements.txt"
    if os.path.isfile(req):
        run_cmd(f"pip install -r {req} 2>&1 | tail -3", timeout=120)
    log("  Video Helper 插件安装完成")


def _install_gguf_plugin():
    """安装 GGUF 插件到 ComfyUI 的 custom_nodes"""
    cn_dir = f"{COMFYUI_DIR}/custom_nodes"
    if os.path.isdir(f"{cn_dir}/ComfyUI-GGUF"):
        return
    os.makedirs(cn_dir, exist_ok=True)
    log("  安装 GGUF 插件...")
    run_cmd(f"git clone https://github.com/city96/ComfyUI-GGUF.git {cn_dir}/ComfyUI-GGUF",
            timeout=60)
    log("  GGUF 插件安装完成")


def _create_extra_model_paths(comfyui_dir):
    """
    在 ComfyUI 目录下创建 extra_model_paths.yaml，
    让 ComfyUI 启动时自动注册 Kaggle Dataset 路径到 folder_paths。

    这是 ComfyUI 原生支持的配置方式，VAELoader/UnetLoaderGGUF/CLIPLoaderGGUF
    的 COMBO 列表会自动包含这些目录中的文件。
    """
    yaml_content = """\
# Kaggle Dataset paths - auto-generated by wan22-ai-series
wan22_models:
  base_path: /kaggle/input/datasets/saysnkaggle/wan2-2-5b-q4-gguf
  unet: model
  clip: model
  vae: model
  diffusion_models: model
  text_encoders: model

wan22_models_sub:
  base_path: /kaggle/input/datasets/saysnkaggle/wan2-2-5b-q4-gguf/model
  unet: .
  clip: .
  vae: .
  unet_gguf: .
  clip_gguf: .
"""
    yaml_path = os.path.join(comfyui_dir or COMFYUI_DIR, "extra_model_paths.yaml")
    with open(yaml_path, "w") as f:
        f.write(yaml_content)
    log(f"  已创建 extra_model_paths.yaml: {yaml_path}")


def _start_comfyui():
    """启动 ComfyUI 服务器（后台）"""
    # 已在运行？
    try:
        urllib.request.urlopen(f"{COMFYUI_URL}/system_stats", timeout=2)
        log("ComfyUI 已在运行")
        return True
    except:
        pass

    # 查找或安装
    result = _find_comfyui()
    if result:
        install_type, path = result
        if install_type == "pip":
            log(f"  ComfyUI (pip): {path}")
        else:
            log(f"  ComfyUI (dir): {path}")
    else:
        _install_comfyui()
        result = _find_comfyui()
        if not result:
            log("❌ ComfyUI 安装后仍无法找到")
            return False
        install_type, path = result

    cwd = path if isinstance(path, str) and os.path.isdir(path) else None
    log("启动 ComfyUI...")
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = "0"

    # 检测 GPU 可用性
    try:
        import torch
        has_gpu = torch.cuda.is_available()
    except:
        has_gpu = False
    gpu_flag = [] if has_gpu else ["--cpu"]
    log(f"  GPU: {'可用' if has_gpu else '不可用(CPU模式)'}")

    # ★ 创建 extra_model_paths.yaml 让 ComfyUI 加载时注册 Dataset 路径 ★
    _create_extra_model_paths(cwd)

    log_file = "/kaggle/working/ai-series/comfyui_startup.log"
    log_fh = open(log_file, "w")   
    if install_type == "pip":
        proc = subprocess.Popen(
            ["python", "-m", "comfy", "main", "--dont-print-server",
             "--preview-method", "none", "--listen", "0.0.0.0", "--port", "8188"] + gpu_flag,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
        )
    else:
        proc = subprocess.Popen(
            ["python", "main.py", "--dont-print-server",
             "--preview-method", "none", "--listen", "0.0.0.0", "--port", "8188"] + gpu_flag,
            cwd=cwd,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            env=env,
        )

    # 快速轮询（3s 间隔），最多 10 分钟
    for i in range(200):
        time.sleep(3)
        try:
            urllib.request.urlopen(f"{COMFYUI_URL}/system_stats", timeout=2)
            log(f"  ComfyUI 就绪 ({(i + 1) * 3}s)")
            log_fh.close()
            return True
        except:
            if i < 5 or i % 20 == 0:
                log(f"  ⏳ 等待... ({(i + 1) * 3}s)")
    # 超时，打印启动日志
    log_fh.close()
    try:
        with open(log_file, "r") as f:
            last_lines = f.readlines()[-30:]
        log("  ❌ ComfyUI 启动超时，最后30行日志:")
        for line in last_lines:
            log(f"    {line.rstrip()}")
    except:
        log(f"  ❌ ComfyUI 启动超时，无法读取 {log_file}")
    return False


def _queue_prompt(workflow):
    """提交工作流到 ComfyUI API"""
    payload = json.dumps({"prompt": workflow, "client_id": "wan22-ai"}).encode()
    req = urllib.request.Request(
        f"{COMFYUI_URL}/prompt",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        log(f"  ComfyUI 错误: HTTP {e.code}")
        log(f"  请求体(前500): {payload[:500]}")
        log(f"  响应体: {body[:300]}")
        raise
    except Exception as e:
        log(f"  请求体(前500): {payload[:500]}")
        raise


def _get_history(prompt_id):
    """获取工作流执行结果"""
    req = urllib.request.Request(f"{COMFYUI_URL}/history/{prompt_id}")
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read())


def _wait_for_completion(prompt_id, timeout=1800):
    """等待工作流执行完成"""
    start = time.time()
    last_log = 0
    while time.time() - start < timeout:
        try:
            history = _get_history(prompt_id)
            if prompt_id in history:
                entry = history[prompt_id]
                status = entry.get("status", {}).get("status_str")
                if status == "success":
                    return entry
                if status == "error":
                    raise RuntimeError(f"工作流执行失败: {entry}")
                # 每30秒打印一次进度
                elapsed = time.time() - start
                if elapsed - last_log >= 30:
                    executors = entry.get("status", {}).get("exec_info", {})
                    queue_remaining = executors.get("queue_remaining", "?")
                    log(f"    ⏳ {elapsed:.0f}s 完成, queue={queue_remaining}")
                    last_log = elapsed
        except urllib.error.HTTPError:
            pass
        time.sleep(5)
    raise TimeoutError(f"工作流 {prompt_id} 超时 ({timeout}s)")


# ============================================================
# 工作流构建
# ============================================================

def _build_wan22_workflow(positive_prompt, negative_prompt, model_path,
                           clip_path, vae_path, width, height, frames,
                           steps, cfg, sampler, scheduler, shift, seed):
    """
    构建 Wan2.2 T2V ComfyUI 工作流（API 格式）。

  节点:
     1: UnetLoaderGGUF — 加载 GGUF UNET
     2: CLIPLoaderGGUF — 加载 text encoder
     3: VAELoader — 加载 VAE
     4: CLIPTextEncode (positive) — 正面提示词
     5: CLIPTextEncode (negative) — 负面提示词
     6: WanImageToVideo — T2V latent 准备（自动生成空 latent）
     7: KSampler — 去噪采样
     8: VAEDecode — 解码 latent 为像素
     9: VHS_VideoCombine — 保存视频
    """
    # 计算 latent 尺寸
    lat_w = width // 8
    lat_h = height // 8
    lat_frames = (frames - 1) // 4 + 1

    # 只传文件名（ComfyUI 通过 extra_model_paths.yaml 注册路径能找到完整路径）
    unet_filename = os.path.basename(model_path)
    clip_filename = os.path.basename(clip_path)

    workflow = {
        "1": {
            "class_type": "UnetLoaderGGUF",
            "inputs": {"unet_name": unet_filename},
        },
        "2": {
            "class_type": "CLIPLoaderGGUF",
            "inputs": {"clip_name": clip_filename, "type": "wan"},
        },
        "3": {
            "class_type": "VAELoader",
            "inputs": {"vae_name": os.path.basename(vae_path)},
        },
        "4": {
            "class_type": "CLIPTextEncode",
            "inputs": {"text": positive_prompt, "clip": ["2", 0]},
        },
        "5": {
            "class_type": "CLIPTextEncode",
            "inputs": {"text": negative_prompt, "clip": ["2", 0]},
        },
        "6": {
            "class_type": "WanImageToVideo",
            "inputs": {
                "positive": ["4", 0],
                "negative": ["5", 0],
                "vae": ["3", 0],
                "width": width,
                "height": height,
                "length": frames,
                "batch_size": 1,
            },
        },
        "7": {
            "class_type": "KSampler",
            "inputs": {
                "model": ["1", 0],
                "positive": ["6", 0],
                "negative": ["6", 1],
                "latent_image": ["6", 2],
                "seed": seed,
                "steps": steps,
                "cfg": cfg,
                "sampler_name": sampler,
                "scheduler": scheduler,
                "denoise": 1.0,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": ["7", 0],
                "vae": ["3", 0],
            },
        },
        "9": {
            "class_type": "VHS_VideoCombine",
            "inputs": {
                "images": ["8", 0],
                "frame_rate": WAN22_DEFAULTS["fps"],
                "loop_count": 0,
                "filename_prefix": "wan22_output",
                "format": "video/h264-mp4",
                "pingpong": False,
                "save_output": True,
            },
        },
    }
    return workflow


# ============================================================
# 主函数
# ============================================================

def _find_wan22_models():
    """查找 Wan2.2 模型文件（Dataset 挂载 或 本地目录）"""
    search_paths = []
    for dataset_dir in ["/kaggle/input/datasets/saysnkaggle/wan2-2-5b-q4-gguf",
                        "/kaggle/input/datasets/saysnkaggle/newdataset",
                        "/kaggle/input/newdataset"]:
        if os.path.isdir(dataset_dir):
            search_paths.append(f"{dataset_dir}/model")
            search_paths.append(f"{dataset_dir}/models")
    search_paths.extend([
        "/kaggle/working/wan22-ai-series/models",
        "/kaggle/working/models",
    ])

    result = {"unet": None, "clip": None, "vae": None}
    for base in search_paths:
        if not os.path.isdir(base):
            continue
        if not result["unet"]:
            for name in ["Wan2.2-TI2V-5B-Q4_K_M.gguf", "Wan2.2-TI2V-5B.gguf"]:
                if os.path.isfile(f"{base}/{name}"):
                    result["unet"] = f"{base}/{name}"
                    break
        if not result["clip"]:
            for name in ["umt5-xxl-encoder-Q4_K_M.gguf", "umt5-xxl-encoder.gguf"]:
                if os.path.isfile(f"{base}/{name}"):
                    result["clip"] = f"{base}/{name}"
                    break
        if not result["vae"]:
            for name in ["Wan2.2_VAE.safetensors", "Wan2.2_VAE.pth"]:
                if os.path.isfile(f"{base}/{name}"):
                    result["vae"] = f"{base}/{name}"
                    break
    return result


def main(storyboard=None):
    log("=" * 50)
    log("Step 4: 视频生成 (Wan2.2-TI2V-5B)")
    log("=" * 50)

    dirs = get_dirs(EPISODE_NUM)
    total = sum(len(s.get("shots", [])) for s in storyboard.get("scenes", []))

    # 模型路径（支持 Dataset 挂载）
    models = _find_wan22_models()
    model_path = models["unet"]
    clip_path = models["clip"]
    vae_path = models["vae"]

    # 检查模型
    for name, path in [("UNET", model_path), ("CLIP", clip_path), ("VAE", vae_path)]:
        if not path:
            log(f"  ❌ {name} 模型未找到")
            return
        size_mb = os.path.getsize(path) / 1e6
        log(f"  ✅ {name}: {os.path.basename(path)} ({size_mb:.0f}MB)")

    # 启动 ComfyUI
    if not _start_comfyui():
        log("❌ ComfyUI 启动失败")
        return

    # Wan2.2 默认参数
    w = WAN22_DEFAULTS["width"]
    h = WAN22_DEFAULTS["height"]
    fps = WAN22_DEFAULTS["fps"]
    steps = WAN22_DEFAULTS["steps"]
    cfg = WAN22_DEFAULTS["cfg"]
    sampler = WAN22_DEFAULTS["sampler"]
    scheduler = WAN22_DEFAULTS["scheduler"]
    shift = WAN22_DEFAULTS["shift"]
    num_frames = WAN22_DEFAULTS["frames_per_shot"]

    log(f"参数: {w}x{h} | {num_frames}f | {steps}步 | CFG={cfg} | {sampler}/{scheduler}")

    # 检查 ComfyUI 是否识别到模型（通过 system_stats 验证）
    try:
        import urllib.request
        stats = json.loads(urllib.request.urlopen(f"{COMFYUI_URL}/system_stats", timeout=5).read())
        devices = stats.get("devices", [])
        log(f"  ComfyUI devices: {[d.get('name','?') for d in devices]}")
    except Exception as e:
        log(f"  ⚠️ system_stats 失败: {e}")

    count = 0
    for scene in storyboard.get("scenes", []):
        for shot in scene.get("shots", []):
            count += 1
            sid = shot["shot_id"]
            ep = storyboard.get("episode", 1)
            out = f"{dirs['videos']}/ep{ep:02d}_{scene['scene_id']}_{sid}.mp4"

            if os.path.exists(out) and os.path.getsize(out) > 100000:
                log(f"  [{count}/{total}] {sid} 跳过(已存在)")
                continue

            # 构建视频 prompt（从分镜 prompt + 动作描述）
            video_prompt = f"{shot.get('prompt', '')}, smooth motion, cinematic, high quality"
            neg_prompt = shot.get("negative_prompt", "blurry, distorted, low quality, static, motionless")

            seed = shot.get("seed", -1)
            if seed < 0:
                seed = WAN22_DEFAULTS["seed"]

            workflow = _build_wan22_workflow(
                positive_prompt=video_prompt,
                negative_prompt=neg_prompt,
                model_path=model_path,
                clip_path=clip_path,
                vae_path=vae_path,
                width=w, height=h,
                frames=num_frames,
                steps=steps, cfg=cfg,
                sampler=sampler, scheduler=scheduler,
                shift=shift, seed=seed,
            )

            try:
                log(f"  [{count}/{total}] {sid} 提交中...")
                result = _queue_prompt(workflow)
                prompt_id = result.get("prompt_id")
                if not prompt_id:
                    raise RuntimeError(f"API 返回无 prompt_id: {result}")

                log(f"  [{count}/{total}] {sid} 等待完成 (id={prompt_id[:8]}...)")
                completion = _wait_for_completion(prompt_id, timeout=1800)

                # 提取输出视频路径
                outputs = completion.get("outputs", {})
                video_output = None
                for node_id, node_output in outputs.items():
                    # VHS_VideoCombine 输出 key 可能是 "gifs" 或 "vhs_filenames"
                    if "gifs" in node_output:
                        gifs = node_output["gifs"]
                        if isinstance(gifs, list) and len(gifs) > 0:
                            video_output = gifs[0]
                            if isinstance(video_output, dict):
                                video_output = video_output.get("fullpath", video_output.get("filename", ""))
                            break
                    if "vhs_filenames" in node_output:
                        video_output = node_output["vhs_filenames"][0]
                        break

                if video_output and os.path.isfile(video_output):
                    # 复制到目标路径
                    import shutil
                    shutil.copy2(video_output, out)
                    dur = shot.get("duration_seconds", 3)
                    size_mb = os.path.getsize(out) / 1e6
                    log(f"  [{count}/{total}] {sid} ✓ ({num_frames}f, {dur}s, {size_mb:.1f}MB)")
                    # 如果文件太小（<50KB），说明可能是静态帧
                    if size_mb < 0.05:
                        log(f"    ⚠️ 文件极小({size_mb:.3f}MB)，可能是静态帧！")
                        _check_comfyui_logs()
                        # 打印 history 中该 prompt 的详细执行信息
                        _print_prompt_history(prompt_id)
                else:
                    log(f"  [{count}/{total}] {sid} 无输出视频")
                    # 调试：打印完整 outputs 结构
                    log(f"    DEBUG outputs keys: {list(outputs.keys()) if outputs else 'None'}")
                    for nid, nout in (outputs or {}).items():
                        if isinstance(nout, dict):
                            for k, v in nout.items():
                                val_preview = str(v)[:200]
                                log(f"    node[{nid}].{k} = {val_preview}")
                    _save_placeholder_video(shot, out, num_frames)

            except Exception as e:
                log(f"  [{count}/{total}] {sid} 失败: {e}")
                _save_placeholder_video(shot, out, num_frames)

    log("视频生成完成")


def _save_placeholder_video(shot, output_path, num_frames):
    from PIL import Image, ImageDraw
    import shutil
    res = WAN22_DEFAULTS["width"]
    img = Image.new("RGB", (res, res), (20, 20, 40))
    draw = ImageDraw.Draw(img)
    draw.rectangle([5, 5, res - 5, res - 5], outline=(100, 100, 200), width=2)
    draw.text((20, 30), "[VIDEO]", fill=(200, 200, 255))
    draw.text((20, 70), shot.get("shot_id", ""), fill=(200, 255, 200))
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    tmp_png = output_path.replace(".mp4", "_tmp.png")
    img.save(tmp_png)
    dur = max(num_frames / WAN22_DEFAULTS["fps"], 1)
    run_cmd(
        f'ffmpeg -y -loop 1 -i "{tmp_png}" -t {dur} '
        f'-c:v libx264 -pix_fmt yuv420p -movflags +faststart "{output_path}" 2>/dev/null'
    )
    if os.path.exists(tmp_png):
        os.remove(tmp_png)


def _check_comfyui_logs():
    """检查 ComfyUI 执行日志中的错误信息"""
    log_file = "/kaggle/working/ai-series/comfyui_startup.log"
    if not os.path.isfile(log_file):
        return
    try:
        with open(log_file, "r") as f:
            lines = f.readlines()
        errors = [l.strip() for l in lines[-200:] if any(k in l.lower() for k in ["error", "warning", "exception", "failed"])]
        if errors:
            log(f"    ComfyUI 最近错误:")
            for e in errors[-10:]:
                log(f"      {e[:200]}")
        else:
            log(f"    ComfyUI 日志无错误")
    except Exception as e:
        log(f"    ⚠️ 无法读日志: {e}")


def _print_prompt_history(prompt_id):
    """打印 prompt 执行历史"""
    try:
        import urllib.request
        history = json.loads(urllib.request.urlopen(f"{COMFYUI_URL}/history/{prompt_id}", timeout=5).read())
        if prompt_id in history:
            entry = history[prompt_id]
            log(f"    === Prompt {prompt_id[:8]} 执行历史 ===")
            for node_id, node_output in entry.get("outputs", {}).items():
                for k, v in node_output.items():
                    if isinstance(v, list) and len(v) > 0:
                        first = v[0]
                        if isinstance(first, dict):
                            info = {kk: str(vv)[:80] for kk, vv in first.items()}
                            log(f"    node[{node_id}].{k}[0] = {info}")
                        else:
                            log(f"    node[{node_id}].{k}[0] = {str(first)[:100]}")
                    elif isinstance(v, (str, int, float, bool)):
                        log(f"    node[{node_id}].{k} = {v}")
            # 也打印 status
            status = entry.get("status", {})
            log(f"    status: {status}")
        else:
            log(f"    history 中无此 prompt_id")
    except Exception as e:
        log(f"    ⚠️ 无法获取 history: {e}")


if __name__ == "__main__":
    dirs = get_dirs(EPISODE_NUM)
    storyboard = load_json(f"{dirs['storyboard']}/episode_{EPISODE_NUM:02d}_storyboard.json")
    main(storyboard)
